name: pyqt5-app-snap-template # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A snap template for desktop App written in pyqt5 # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pyqt5-app-snap-template:
    command: desktop-launch $SNAP/app
    plugs: [unity7, x11, opengl]

parts:
  app:
    plugin: dump
    source: ./src
    organize:
      main.py: app

    stage-packages:
      - qtdeclarative5-qtquick2-plugin
      - python3-pyqt5
      - python3-pyqt5.qtquick
      - overlay-scrollbar-gtk2
      - libatk-adaptor
      - libcanberra-gtk-module
      - unity-gtk3-module
    after: [desktop-qt5]
